name: app
description: An empty Aqueduct application.
version: 0.0.1

environment:
  sdk: ">=2.0.0 <3.0.0"

dependencies:
  aqueduct: 3.3.0+1
  cloudbase_dart: ^0.0.3

dev_dependencies:
  test: ^1.0.0
  aqueduct_test: ^1.0.0